# Generated by Django 4.1.2 on 2022-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('PIS', models.CharField(max_length=11)),
                ('Cargo', models.CharField(max_length=50)),
                ('Salario', models.CharField(max_length=10)),
                ('Contato', models.CharField(max_length=50)),
            ],
        ),
    ]
