# Generated by Django 4.1.2 on 2022-12-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='franquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProprietario', models.CharField(max_length=50)),
                ('CNPJ', models.CharField(max_length=14)),
                ('Endereco', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
