# Generated by Django 4.1.2 on 2022-12-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('CPF', models.CharField(max_length=11)),
                ('Endereco', models.CharField(max_length=100)),
                ('Cartao', models.CharField(max_length=50)),
                ('Contato', models.CharField(max_length=50)),
            ],
        ),
    ]
